version: '3'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_CACHE', true);
        define('WP_CACHE_KEY_SALT', 'your_cache_salt_here');
    volumes:
      - wordpress_data:/var/www/html
    deploy:
      replicas: 2

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"

volumes:
  wordpress_data:
  db_data:

